### ISSUE TITLE
iOS 登录没有回调消息

### ISSUE THREAD

**Issue by goyourfly** [v7lin/fake_weibo#11]
您好，非常感谢开发这么棒的开源库，但是我在 iOS 上使用登录的时候没有回调消息，我是按照您的文档写的，您知道可能是什么原因吗？

**Comment by v7lin** [comment]
1. URL scheme 没配置好
2. 你接了其他需要改APPdelegate的插件

先发 scheme 配置截图我看看吧

**Comment by goyourfly** [comment]
这个是 Scheme 配置
![image](https://user-images.githubusercontent.com/7019862/63173458-86b00c80-c072-11e9-853c-c6f8c9b0b9ff.png)

**Comment by goyourfly** [comment]
现在的现象是：页面能跳回到自己应用，但是 weibo.authResp().listen(_listenAuth);` 这个回调没有消息

**Comment by v7lin** [comment]
appdelegate. m有改过吗？

**Comment by goyourfly** [comment]
这个有改过，加了一些其他的逻辑

**Comment by v7lin** [comment]
爱莫能助了 … 自己断点调试吧 …

**Comment by goyourfly** [comment]
哦哦，好吧，非常感谢

**Comment by SwordBearer** [comment]
重复回答一下，我也遇到这个问题了，我AppDelegate.m 重写了 openURL ，然后导致微博回调无法被处理，是因为这样就拦截了 fake_weibo 的回调处理逻辑，我的解决办法是，在 openURL 方法最后面加上这句：

```
    //调用已重写方法去完成微博处理
    return [super application:application openURL:url options:options];
```

希望有所帮助
