### ISSUE TITLE
 设置了redirectUrl还是一样登录不了，还是报 redirect_uri_mismath，确认url是对的

### ISSUE THREAD

**Issue by jialingWei** [v7lin/fake_weibo#12]
Weibo _weibo = Weibo()
   ..registerApp(
     appKey: _WEIBO_APP_KEY,
    scope: _WEIBO_SCOPE,
     redirectUrl: _WEIBOURL,
  );

**Comment by v7lin** [comment]
两处地方要传redirectURL

**Comment by jialingWei** [comment]
非常感谢解答答，我已经传了
weibo.auth(
   appKey: _WEIBO_APP_KEY,
    scope: _WEIBO_SCOPE,
   redirectUrl: _WEIBOURL
   );
是不是填的url报了404的原因

**Comment by v7lin** [comment]
😅 404？还不如都不传，直接使用新浪默认的URL

**Comment by jialingWei** [comment]
之前没有填写url，然后报了redirect_uri_mismath😭，然后以为是没有填新浪上面的url，然后就写了报404的url上去。。😭

**Comment by v7lin** [comment]
新浪后台上你填了啥URL？

**Comment by jialingWei** [comment]
就是报了404的url。。我叫他们改一下哈哈哈哈哈，再测试一下

**Comment by jialingWei** [comment]
已经可以了，非常感谢，就是因为redirectUrl是404的原因
