### ISSUE TITLE
Assertion failed: (NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]), function +[UIDevice(WBSDKHelpers) getUniqueStrByUUID], file /Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m, line 116.

### ISSUE THREAD

**Issue by Deain** [v7lin/fake_weibo#13]
Xcode更新后，运行报错，

**Comment by v7lin** [comment]
podfile.lock发出来看看

**Comment by Deain** [comment]
> podfile.lock发出来看看

  - Weibo_SDK (3.2.3)

**Comment by Deain** [comment]
> podfile.lock发出来看看

  - fake_weibo (0.0.1):
    - Flutter
    - Weibo_SDK (~> 3.2.3)

**Comment by Deain** [comment]
> podfile.lock发出来看看
- Weibo_SDK (~> 3.2.3)
真机运行正常，模拟器更新ios13后运行失败
weiboSDK pod还未到3.2.5 ![issue408]https://github.com/sinaweibosdk/weibo_ios_sdk/issues/408

**Comment by v7lin** [comment]
好的

**Comment by v7lin** [comment]
fake_weibo: ^0.2.4
