### ISSUE TITLE
微博分享网页效果不理想，有没有办法加上文字或者图片呢？

### ISSUE THREAD

**Issue by iperfectapp** [v7lin/fake_weibo#15]
![QQ图片20191020233129](https://user-images.githubusercontent.com/3021764/67161961-16837700-f392-11e9-956b-2fe07230f307.jpg)

![image](https://user-images.githubusercontent.com/3021764/67161968-49c60600-f392-11e9-8ebd-d14182b5d722.png)

**Comment by v7lin** [comment]
推荐图文分享，分享内容后面跟上url

**Comment by iperfectapp** [comment]
Specs satisfying the `fake_weibo (from `.symlinks/plugins/fake_weibo/ios`)` dependency were found, but they required a higher minimum deployment target.

iOS端所需最低版本是多少呢？

**Comment by v7lin** [comment]
看podspec

**Comment by iperfectapp** [comment]
非常感谢
