### ISSUE TITLE
集成微博登陆后，ios端出现版本兼容问题

### ISSUE THREAD

**Issue by JiangJuHong** [v7lin/fake_weibo#17]
执行 pod install 时，出现的错误如下：

> [!] CocoaPods could not find compatible versions for pod "fake_weibo":
>   In Podfile:
>     fake_weibo (from `.symlinks/plugins/fake_weibo/ios`)
> 
> Specs satisfying the `fake_weibo (from `.symlinks/plugins/fake_weibo/ios`)` dependency were found, but they required a higher minimum deployment target.
> 
> [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
>

**Comment by v7lin** [comment]
修改podfile，将platform改成9.0

**Comment by JiangJuHong** [comment]
@v7lin  它解决这个问题，感谢
