### ISSUE TITLE
更新到flutter 1.12版本，fake_weibo插件用不了，运行报下面的错，把fake_weibo插件去掉运行正常。

### ISSUE THREAD

**Issue by luckmlc** [v7lin/fake_weibo#18]
更新到flutter 1.12版本，ios 下fake_weibo插件用不了，运行报下面的错，把fake_weibo插件去掉运行正常。

android 使用正常。

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "fake_weibo":
      In Podfile:
        fake_weibo (from `.symlinks/plugins/fake_weibo/ios`)

    Specs satisfying the `fake_weibo (from `.symlinks/plugins/fake_weibo/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by v7lin** [comment]
podfile内容付上来

**Comment by v7lin** [comment]
看log和插件没半毛钱关系

**Comment by luckmlc** [comment]
好了，把 ios deployment target 从8.0改成9.0就好了，以前旧版本好像是不用改对吧。

**Comment by v7lin** [comment]
都要改，微博iOS SDK最低支持9.0，flutter默认8.0

**Comment by luckmlc** [comment]
> 都要改，微博iOS SDK最低支持9.0，flutter默认8.0

嗯，可能之前记错了，一直在android下开发，切到ios发现问题，谢谢！
