### ISSUE TITLE
安卓 demo 在雷电模拟器闪退，真机登录授权时出现sso package or sign error，9.0版本

### ISSUE THREAD

**Issue by 3067200952** [v7lin/fake_weibo#4]

**Comment by v7lin** [comment]
大哥 ... 咱不讨论模拟器 ... 真机上，请替换成自己在微博开放平台上注册的应用相关信息

**Comment by 3067200952** [comment]
行吧，只是用模拟器测试会比较方便，能调屏幕比例

**Comment by v7lin** [comment]
咱能用谷歌官方的模拟器吗？第三方模拟器鬼知道他们怎么魔改底层 ... 出现兼容问题，也怪不到flutter和weibo sdk闪退 ... 比较他们都有so库

**Comment by 3067200952** [comment]
已换模拟器，好了
