### ISSUE TITLE
分享图片时，应该也可以分享文本

### ISSUE THREAD

**Issue by jlcool** [v7lin/fake_weibo#5]
分享图片时，应该也可以分享文本

**Comment by jlcool** [comment]
自己改了下但是闪退了

**Comment by v7lin** [comment]
下班后看一下

**Comment by v7lin** [comment]
好了，0.2.1版本就有这功能了

**Comment by jlcool** [comment]
@v7lin  我这里android闪退，ios没试

**Comment by v7lin** [comment]
有没有log？

**Comment by jlcool** [comment]
No package identifier when getting name for resource number 0x00000000
这个算吗

**Comment by v7lin** [comment]
看看exception

**Comment by jlcool** [comment]
分享的时候跳到黑屏，之后微博没打卡，app就断开连接，没有别的exception

**Comment by v7lin** [comment]
这就蛋疼了 ... 提供一下机型信息。还有，这个工程的Demo也会崩溃么？如果不能，提供一个Demo。

**Comment by jlcool** [comment]
是图片大小的问题，原来可以分享的图片新方法无法分享了，具体是多少大小的限制你知道吗

**Comment by v7lin** [comment]
小图用 uint8list，大图用uri

**Comment by v7lin** [comment]
这是因为Android的intent传递数据大小是有限制的，intent传递数据大小限制为1M

**Comment by v7lin** [comment]
iOS无此限制 ...

**Comment by jlcool** [comment]
恩恩，可以了，感谢，可以写个注释说明，免得使用imageData闪退了

**Comment by v7lin** [comment]
好的ヾ ^_^♪
