### ISSUE TITLE
您好！我看到您解决了expiresIn -> expiresTime问题，并且版本号改成4.0.1了，为什么我这里更新不了您的4.0.1的版本呢？并且您的pub.dev上显示的最新版本号还是4.0.0. 希望您尽快修改一下，我们的APP 这周要发布生产环境需要用到这个新版本，谢谢！

### ISSUE THREAD

**Issue by 15949893621** [v7lin/fake_weibo#51]
![截屏2022-08-01 11 19 11](https://user-images.githubusercontent.com/17999816/182065491-7916901d-d025-4517-96dd-292329f4bdbf.png)

**Comment by droplet-js** [comment]
嗯，因为没有测试条件，你可以先用 git 方式引入，帮忙测试一下，如果没有问题，我就把这东西给发了

**Comment by 15949893621** [comment]
您好！我这里刚刚测试了一下，看到
![截屏2022-08-01 12 06 12](https://user-images.githubusercontent.com/17999816/182070574-25ce9799-300b-4a87-8324-3ab0f7486909.png)
数据正常了，您可以更新了。

**Comment by droplet-js** [comment]
@15949893621 能否帮忙看一下 iOS 的数据？

**Comment by droplet-js** [comment]
你这截图上的数据，貌似这过期时间为 30 天 ... 这似乎和微博SDK文档描述对不上 ...
