### ISSUE TITLE
Android12 分享图片 shareImage 报TransactionTooLargeException问题

### ISSUE THREAD

**Issue by Ucoon** [v7lin/fake_weibo#54]
机型：红米k40，Android12
概率：必现
复现步骤：通过截屏repaintKey获取到imageData之后，调用shareImage会报TransactionTooLargeException问题，在低版本Android机子上使用正常

**Comment by droplet-js** [comment]
不建议用 shareImage，建议用 shareMultiImage。原因是微博SDK比较坑爹，shareImage不支持FileProvider模式，用的是Intent传递图片，Intent传递的数据是有限的。

**Comment by Sand2Dev** [comment]
可是最新的包里没有 shareMultiImage 方法了啊
