### ISSUE TITLE
使用网页登录时，部分手机不能正确返回。在使用微博极速版时，不能跳转授权

### ISSUE THREAD

**Issue by 3067200952** [v7lin/fake_weibo#6]

**Comment by 3067200952** [comment]
米8和红米note7pro不能返回，iOS也不行，一台魅族可以

**Comment by v7lin** [comment]
iOS请检查readme配置，以及你是否曾经接其他插件而修改了appdelegate.m

**Comment by v7lin** [comment]
米8和红米Pro问题，我只能说，我去官方看看有没有sdk更新了 …

**Comment by 3067200952** [comment]
ios没问题，不能网页登录还有其他机型也有出现，不同品牌的，不知道什么问题

**Comment by 3067200952** [comment]
失败的时候返回值为-1，屏幕显示success

**Comment by 3067200952** [comment]
网页没有自动关闭

**Comment by v7lin** [comment]
好的，今晚我去更新一下最新的新浪微博Android SDK

**Comment by 3067200952** [comment]
微博极速版是什么原因呢？网页的话，倒是可以直接禁用

**Comment by v7lin** [comment]
😂 微博官方sdk如果不支持我也没辙，不是么。今晚先升级sdk再说。

**Comment by 3067200952** [comment]
升级怎么样了？

**Comment by v7lin** [comment]
已升级
