### ISSUE TITLE
使用android studio x86模拟器调试时闪退

### ISSUE THREAD

**Issue by 2534290808** [v7lin/fake_weibo#9]
使用android studio x86模拟器调试时会因缺少libwind.so而闪退，请问有解决办法吗？

**Comment by v7lin** [comment]
真机上调试不好吗？

**Comment by 2534290808** [comment]
我只是引入你的这个插件:smile: ,然后就运行不起来，没打算用模拟器调试微博，只是画页面而已，就连app都打不开直接闪退了，

**Comment by v7lin** [comment]
那是你引入的其他library里的so不全

**Comment by 2534290808** [comment]
嗯，应该是，似乎原生的sdk也有人提出这个问题

**Comment by v7lin** [comment]
所以，还是关了吧 …
